name: API Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [sync-player]

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Read existing data
        run: |
          if [ -f api/sync.json ]; then
            echo "Existing data found."
          else
            echo "[]" > api/sync.json
          fi

      - name: Update player data
        run: |
          echo '${{ github.event.client_payload.data }}' > api/sync.json

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add api/sync.json
          git commit -m "Updated player data"
          git push
